-- Create tables
CREATE TABLE CUSTOMER (
    CID INT PRIMARY KEY,
    EMAIL VARCHAR(255),
    ADDRESS VARCHAR(255),
    PHONE VARCHAR(20),
    FNAME VARCHAR(50),
    LNAME VARCHAR(50),
    STATUS VARCHAR(20),
    ACCOUNT VARCHAR(50) UNIQUE, 
    PASSWORD VARCHAR(255)
);
CREATE TABLE SILVER_AND_ABOVE (
    SACID INT PRIMARY KEY,
    CID INT,
    FOREIGN KEY (CID) REFERENCES CUSTOMER(CID)
);

CREATE TABLE CREDIT_CARD (
    CARDNUMBER VARCHAR(16) PRIMARY KEY,
    SECNUMBER VARCHAR(4),
    CARDOWNERNAME VARCHAR(100),
    CARDTYPE VARCHAR(20),
    BILLINGADDRESS VARCHAR(255),
    EXPDATE DATE,
    TRANTAG VARCHAR(16),
    TDATE DATE,
    TOTALAMOUNT INT,
    CSNAME VARCHAR(16),
    FOREIGN KEY (CSNAME) REFERENCES SHIP_ADDRESS(SANAME)
);

CREATE TABLE STORED_CARD (
    SCARDNUMBER VARCHAR(16) PRIMARY KEY,
    SCID INT,
    FOREIGN KEY (SCID) REFERENCES REFERENCES CUSTOMER(CID)
);

CREATE TABLE SHIP_ADDRESS (
	SCID INT,
    SANAME VARCHAR(50) PRIMARY KEY,
    SNUMBER INT,
    STREET VARCHAR(255),
    ZIP VARCHAR(10),
    CITY VARCHAR(50),
    RECEPIENTNAME VARCHAR(100),
    COUNTRY VARCHAR(50),
    STATE VARCHAR(50),
	FOREIGN KEY (SCID) REFERENCES CUSTOMER(CID)
);
CREATE TABLE TRANSACTION (
    TCARTID INT PRIMARY KEY,
    TSANAME VARCHAR(50),
    TCARDNUMBER VARCHAR(16),
    TRANTAG INT,
    TDATE DATE,
    TOTALAMOUNT DECIMAL(10, 2),
    FOREIGN KEY (TSANAME) REFERENCES SHIP_ADDRESS(SANAME),
    FOREIGN KEY (TCARDNUMBER) REFERENCES CREDIT_CARD(CARDNUMBER),
    FOREIGN KEY (TCARTID) REFERENCES BASKET(CARTID)
);

CREATE TABLE BASKET (
	CARTID INT PRIMARY KEY,
    BCID INT,
    BCARDNUMBER VARCHAR(16),
    BSANAME VARCHAR(50),
    FOREIGN KEY (BCARDNUMBER) REFERENCES CREDIT_CARD(CARDNUMBER),
    FOREIGN KEY (BSANAME) REFERENCES SHIP_ADDRESS(SANAME)
);

CREATE TABLE APPEARS_IN (
	QUANTITY INT,
	PRICESOLD DECIMAL(10, 2),
    ACARTID INT,
    APRODUCEDID INT,
    PRIMARY KEY (ACARTID, APRODUCEDID),
    FOREIGN KEY (ACARTID) REFERENCES BASKET(CARTID),
    FOREIGN KEY (APRODUCEDID) REFERENCES PRODUCT(PRODUCTID)
);

CREATE TABLE PRODUCT (
    PRODUCTID INT PRIMARY KEY,
    PNAME VARCHAR(100),
    PPRICE DECIMAL(10, 2),
    PTYPE VARCHAR(50),
    PQUANTITY INT,
    PDESCRIPTION VARCHAR(255)
);

CREATE TABLE OFFER_PRODUCT (
    OPRODUCTID INT  PRIMARY KEY,
    OFFERPRICE DECIMAL(10, 2),
    FOREIGN KEY (OPRODUCTID) REFERENCES PRODUCT(PRODUCTID)
);

CREATE TABLE COMPUTER (
    CPRODUCTID INT PRIMARY KEY,
    CPUTYPE VARCHAR(50),
    FOREIGN KEY (CPRODUCTID) REFERENCES PRODUCT(PRODUCTID)
);

CREATE TABLE PRINTER (
    PPRODUCTID INT PRIMARY KEY,
    RESOLUTION VARCHAR(50),
    PRINTERTYPE VARCHAR(50),
    FOREIGN KEY (PPRODUCTID) REFERENCES PRODUCT(PRODUCTID)
);

CREATE TABLE LAPTOP (
    LPRODUCTID INT PRIMARY KEY,
    BATTERYTYPE VARCHAR(50),
    WEIGHT DECIMAL(5, 2),
    FOREIGN KEY (LPRODUCTID) REFERENCES PRODUCT(PRODUCTID)
);